version: '3.7'
services:
  php:
    build:
      context: ../../docker/php
      dockerfile: Dockerfile.alpine
      args:
        PHP_IMAGE_TAG: 8.0-cli-alpine3.13
        LIBRDKAFKA_VERSION: v1.6.1
        PHP_EXTENSION: php-kafka/php-simple-kafka-client
        PHP_EXTENSION_VERSION: v0.1.1
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
  redpanda:
    entrypoint:
      - /usr/bin/rpk
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29097,OUTSIDE://0.0.0.0:9097
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29097,OUTSIDE://redpanda:9097
      - --check=false
    image: vectorized/redpanda:v21.4.12
    ports:
      - 9097:9097
      - 29097:29097
